hospital.name=Dr. Chanda Jain Nursing Home
hospital.name.hindi=डॉ. चंदा  जैन  नर्सिंग  होम
hospital.address=323, Civil Ward No. 7, Damoh. (MP) Pin - 470661
hospital.address.hindi=सिविल वार्ड नंबर 7 दमोह (म. प्र.)
hospital.registration.number=NH/9255/JUN-2023
hospital.phone=07812-222441
hospital.mobile=6263169195
hospital.logo.path=images/logo.png
hospital.other.description=* रविवार अवकाश *

hospital.doctors.list=dr_anuj, dr_swati

dr_anuj.name=Dr. Anuj Jain
dr_anuj.name.hindi=डॉ. अनुज जैन
dr_anuj.qualification=MBBS, DGO
dr_anuj.description.rows=3
dr_anuj.description.row.1=स्त्री रोग विशेषज्ञ CF. Sr. No. Addl./MPMC-7259
dr_anuj.description.row.2=FMF LONDON CERTIFIED SONOGRAPHER [ID 174684]
dr_anuj.description.row.3=मिलने का समय सुबह 10 बजे से शाम 5 बजे तक
dr_anuj.fees=120


dr_swati.name=Dr. Swati Jain
dr_swati.name.hindi=डॉ. स्वाती जैन
dr_swati.qualification=MBBS, DGO
dr_swati.description.rows=3
dr_swati.description.row.1=स्त्री रोग विशेषज्ञ CF. Sr. No. Addl./MPMC-7259
dr_swati.description.row.2=CERTIFIED COLPOSCOPIST [ MUMBAI ]
dr_swati.description.row.3=मिलने का समय सुबह 11बजे से 1 बजे, 1:30 से शाम 3 बजे
dr_swati.fees=120


